### ISSUE TITLE
SCSS variables auto-export

### ISSUE THREAD

**Issue by Ebuall** [glortho/styled-import#12]
If you have a sass variables meant for export, would be nice to use them in your JS. You can already do that with CSS modules export, but you still need to specify each variable twice. You can't just use library variables without some glue code. 
I don't know if that fits your domain, but seems close and useful not only for styled components.

SASS modules export example:
```scss
$color-blue: #0000FF;
:export {
  colorBlue: $color-blue;
}
```
